set(GLFW_LIBRARY_DIR "$ENV{GLFW_DIR}/lib")
set(GLFW_BINARY_DIR  "$ENV{GLFW_DIR}/lib")
set(GLFW_DLLS        "${GLFW_BINARY_DIR}/glfw3.dll")

# exported
set(GLFW_INCLUDE_DIRS "$ENV{GLFW_DIR}/include")
set(GLFW_LIBRARIES    "${GLFW_LIBRARY_DIR}/glfw3dll.lib")

MESSAGE(STATUS ${GLFW_INCLUDE_DIRS})
MESSAGE(STATUS ${GLFW_LIBRARY_DIR})
MESSAGE(STATUS ${GLFW_LIBRARIES})
MESSAGE(STATUS ${GLFW_BINARY_DIR})
MESSAGE(STATUS ${GLFW_DLLS})
